/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as charactersIndexRouteImport } from './routes/(characters)/index'
import { Route as charactersCharacterIdRouteImport } from './routes/(characters)/$characterId'

const charactersIndexRoute = charactersIndexRouteImport.update({
  id: '/(characters)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const charactersCharacterIdRoute = charactersCharacterIdRouteImport.update({
  id: '/(characters)/$characterId',
  path: '/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$characterId': typeof charactersCharacterIdRoute
  '/': typeof charactersIndexRoute
}
export interface FileRoutesByTo {
  '/$characterId': typeof charactersCharacterIdRoute
  '/': typeof charactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(characters)/$characterId': typeof charactersCharacterIdRoute
  '/(characters)/': typeof charactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$characterId' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$characterId' | '/'
  id: '__root__' | '/(characters)/$characterId' | '/(characters)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  charactersCharacterIdRoute: typeof charactersCharacterIdRoute
  charactersIndexRoute: typeof charactersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(characters)/': {
      id: '/(characters)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof charactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(characters)/$characterId': {
      id: '/(characters)/$characterId'
      path: '/$characterId'
      fullPath: '/$characterId'
      preLoaderRoute: typeof charactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  charactersCharacterIdRoute: charactersCharacterIdRoute,
  charactersIndexRoute: charactersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
